package Modelo;
// Generated 10-20-2014 02:19:12 PM by Hibernate Tools 3.6.0



/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private int idactivdad;
     private Plantillaactividad plantillaactividad;
     private Usuario usuario;
     private Character estadoactividad;

    public Actividad() {
    }

	
    public Actividad(int idactivdad, Plantillaactividad plantillaactividad, Usuario usuario) {
        this.idactivdad = idactivdad;
        this.plantillaactividad = plantillaactividad;
        this.usuario = usuario;
    }
    public Actividad(int idactivdad, Plantillaactividad plantillaactividad, Usuario usuario, Character estadoactividad) {
       this.idactivdad = idactivdad;
       this.plantillaactividad = plantillaactividad;
       this.usuario = usuario;
       this.estadoactividad = estadoactividad;
    }
   
    public int getIdactivdad() {
        return this.idactivdad;
    }
    
    public void setIdactivdad(int idactivdad) {
        this.idactivdad = idactivdad;
    }
    public Plantillaactividad getPlantillaactividad() {
        return this.plantillaactividad;
    }
    
    public void setPlantillaactividad(Plantillaactividad plantillaactividad) {
        this.plantillaactividad = plantillaactividad;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Character getEstadoactividad() {
        return this.estadoactividad;
    }
    
    public void setEstadoactividad(Character estadoactividad) {
        this.estadoactividad = estadoactividad;
    }




}


