package Modelo;
// Generated 10-18-2014 09:44:40 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String idempleado;
     private UnidadOrganizativa unidadOrganizativa;
     private Cargo cargo;
     private String nombres;
     private String apepaterno;
     private String apematerno;
     private String correo;
     private char estadoempleado;
     private Date fechaini;
     private Date fechafin;
     private Set desafectacionsForEmpIdempleado = new HashSet(0);
     private Set desafectacionsForIdempleado = new HashSet(0);
     private Set inventariosForEmpIdempleado = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set activos = new HashSet(0);
     private Set inventariosForIdempleado = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(String idempleado, UnidadOrganizativa unidadOrganizativa, Cargo cargo, String nombres, char estadoempleado, Date fechaini) {
        this.idempleado = idempleado;
        this.unidadOrganizativa = unidadOrganizativa;
        this.cargo = cargo;
        this.nombres = nombres;
        this.estadoempleado = estadoempleado;
        this.fechaini = fechaini;
    }
    public Empleado(String idempleado, UnidadOrganizativa unidadOrganizativa, Cargo cargo, String nombres, String apepaterno, String apematerno, String correo, char estadoempleado, Date fechaini, Date fechafin, Set desafectacionsForEmpIdempleado, Set desafectacionsForIdempleado, Set inventariosForEmpIdempleado, Set usuarios, Set activos, Set inventariosForIdempleado) {
       this.idempleado = idempleado;
       this.unidadOrganizativa = unidadOrganizativa;
       this.cargo = cargo;
       this.nombres = nombres;
       this.apepaterno = apepaterno;
       this.apematerno = apematerno;
       this.correo = correo;
       this.estadoempleado = estadoempleado;
       this.fechaini = fechaini;
       this.fechafin = fechafin;
       this.desafectacionsForEmpIdempleado = desafectacionsForEmpIdempleado;
       this.desafectacionsForIdempleado = desafectacionsForIdempleado;
       this.inventariosForEmpIdempleado = inventariosForEmpIdempleado;
       this.usuarios = usuarios;
       this.activos = activos;
       this.inventariosForIdempleado = inventariosForIdempleado;
    }
   
    public String getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(String idempleado) {
        this.idempleado = idempleado;
    }
    public UnidadOrganizativa getUnidadOrganizativa() {
        return this.unidadOrganizativa;
    }
    
    public void setUnidadOrganizativa(UnidadOrganizativa unidadOrganizativa) {
        this.unidadOrganizativa = unidadOrganizativa;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApepaterno() {
        return this.apepaterno;
    }
    
    public void setApepaterno(String apepaterno) {
        this.apepaterno = apepaterno;
    }
    public String getApematerno() {
        return this.apematerno;
    }
    
    public void setApematerno(String apematerno) {
        this.apematerno = apematerno;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public char getEstadoempleado() {
        return this.estadoempleado;
    }
    
    public void setEstadoempleado(char estadoempleado) {
        this.estadoempleado = estadoempleado;
    }
    public Date getFechaini() {
        return this.fechaini;
    }
    
    public void setFechaini(Date fechaini) {
        this.fechaini = fechaini;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public Set getDesafectacionsForEmpIdempleado() {
        return this.desafectacionsForEmpIdempleado;
    }
    
    public void setDesafectacionsForEmpIdempleado(Set desafectacionsForEmpIdempleado) {
        this.desafectacionsForEmpIdempleado = desafectacionsForEmpIdempleado;
    }
    public Set getDesafectacionsForIdempleado() {
        return this.desafectacionsForIdempleado;
    }
    
    public void setDesafectacionsForIdempleado(Set desafectacionsForIdempleado) {
        this.desafectacionsForIdempleado = desafectacionsForIdempleado;
    }
    public Set getInventariosForEmpIdempleado() {
        return this.inventariosForEmpIdempleado;
    }
    
    public void setInventariosForEmpIdempleado(Set inventariosForEmpIdempleado) {
        this.inventariosForEmpIdempleado = inventariosForEmpIdempleado;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getActivos() {
        return this.activos;
    }
    
    public void setActivos(Set activos) {
        this.activos = activos;
    }
    public Set getInventariosForIdempleado() {
        return this.inventariosForIdempleado;
    }
    
    public void setInventariosForIdempleado(Set inventariosForIdempleado) {
        this.inventariosForIdempleado = inventariosForIdempleado;
    }




}


