package Modelo;
// Generated 10-18-2014 09:44:40 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mantenimiento generated by hbm2java
 */
public class Mantenimiento  implements java.io.Serializable {


     private int idmantenimiento;
     private Activo activo;
     private String dscmantenimiento;
     private BigDecimal costomantenimiento;
     private Date fechaentregado;
     private Date fechaestimadarecepcion;
     private Date fecharealrecepcion;
     private char estadomantenimiento;
     private Set personas = new HashSet(0);

    public Mantenimiento() {
    }

	
    public Mantenimiento(int idmantenimiento, String dscmantenimiento, BigDecimal costomantenimiento, Date fechaentregado, Date fechaestimadarecepcion, Date fecharealrecepcion, char estadomantenimiento) {
        this.idmantenimiento = idmantenimiento;
        this.dscmantenimiento = dscmantenimiento;
        this.costomantenimiento = costomantenimiento;
        this.fechaentregado = fechaentregado;
        this.fechaestimadarecepcion = fechaestimadarecepcion;
        this.fecharealrecepcion = fecharealrecepcion;
        this.estadomantenimiento = estadomantenimiento;
    }
    public Mantenimiento(int idmantenimiento, Activo activo, String dscmantenimiento, BigDecimal costomantenimiento, Date fechaentregado, Date fechaestimadarecepcion, Date fecharealrecepcion, char estadomantenimiento, Set personas) {
       this.idmantenimiento = idmantenimiento;
       this.activo = activo;
       this.dscmantenimiento = dscmantenimiento;
       this.costomantenimiento = costomantenimiento;
       this.fechaentregado = fechaentregado;
       this.fechaestimadarecepcion = fechaestimadarecepcion;
       this.fecharealrecepcion = fecharealrecepcion;
       this.estadomantenimiento = estadomantenimiento;
       this.personas = personas;
    }
   
    public int getIdmantenimiento() {
        return this.idmantenimiento;
    }
    
    public void setIdmantenimiento(int idmantenimiento) {
        this.idmantenimiento = idmantenimiento;
    }
    public Activo getActivo() {
        return this.activo;
    }
    
    public void setActivo(Activo activo) {
        this.activo = activo;
    }
    public String getDscmantenimiento() {
        return this.dscmantenimiento;
    }
    
    public void setDscmantenimiento(String dscmantenimiento) {
        this.dscmantenimiento = dscmantenimiento;
    }
    public BigDecimal getCostomantenimiento() {
        return this.costomantenimiento;
    }
    
    public void setCostomantenimiento(BigDecimal costomantenimiento) {
        this.costomantenimiento = costomantenimiento;
    }
    public Date getFechaentregado() {
        return this.fechaentregado;
    }
    
    public void setFechaentregado(Date fechaentregado) {
        this.fechaentregado = fechaentregado;
    }
    public Date getFechaestimadarecepcion() {
        return this.fechaestimadarecepcion;
    }
    
    public void setFechaestimadarecepcion(Date fechaestimadarecepcion) {
        this.fechaestimadarecepcion = fechaestimadarecepcion;
    }
    public Date getFecharealrecepcion() {
        return this.fecharealrecepcion;
    }
    
    public void setFecharealrecepcion(Date fecharealrecepcion) {
        this.fecharealrecepcion = fecharealrecepcion;
    }
    public char getEstadomantenimiento() {
        return this.estadomantenimiento;
    }
    
    public void setEstadomantenimiento(char estadomantenimiento) {
        this.estadomantenimiento = estadomantenimiento;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


