package Modelo;
// Generated 10-20-2014 02:19:12 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private int idmunicipio;
     private Departamento departamento;
     private String nmbmunicipio;
     private Set ubicacionfisicas = new HashSet(0);

    public Municipio() {
    }

	
    public Municipio(int idmunicipio, Departamento departamento, String nmbmunicipio) {
        this.idmunicipio = idmunicipio;
        this.departamento = departamento;
        this.nmbmunicipio = nmbmunicipio;
    }
    public Municipio(int idmunicipio, Departamento departamento, String nmbmunicipio, Set ubicacionfisicas) {
       this.idmunicipio = idmunicipio;
       this.departamento = departamento;
       this.nmbmunicipio = nmbmunicipio;
       this.ubicacionfisicas = ubicacionfisicas;
    }
   
    public int getIdmunicipio() {
        return this.idmunicipio;
    }
    
    public void setIdmunicipio(int idmunicipio) {
        this.idmunicipio = idmunicipio;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNmbmunicipio() {
        return this.nmbmunicipio;
    }
    
    public void setNmbmunicipio(String nmbmunicipio) {
        this.nmbmunicipio = nmbmunicipio;
    }
    public Set getUbicacionfisicas() {
        return this.ubicacionfisicas;
    }
    
    public void setUbicacionfisicas(Set ubicacionfisicas) {
        this.ubicacionfisicas = ubicacionfisicas;
    }




}


