package Modelo;
// Generated 10-20-2014 02:19:12 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Plantillaactividad generated by hbm2java
 */
public class Plantillaactividad  implements java.io.Serializable {


     private int idplantilla;
     private Rol rol;
     private String dscplantilla;
     private char estadoplantilla;
     private Set actividads = new HashSet(0);

    public Plantillaactividad() {
    }

	
    public Plantillaactividad(int idplantilla, Rol rol, String dscplantilla, char estadoplantilla) {
        this.idplantilla = idplantilla;
        this.rol = rol;
        this.dscplantilla = dscplantilla;
        this.estadoplantilla = estadoplantilla;
    }
    public Plantillaactividad(int idplantilla, Rol rol, String dscplantilla, char estadoplantilla, Set actividads) {
       this.idplantilla = idplantilla;
       this.rol = rol;
       this.dscplantilla = dscplantilla;
       this.estadoplantilla = estadoplantilla;
       this.actividads = actividads;
    }
   
    public int getIdplantilla() {
        return this.idplantilla;
    }
    
    public void setIdplantilla(int idplantilla) {
        this.idplantilla = idplantilla;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getDscplantilla() {
        return this.dscplantilla;
    }
    
    public void setDscplantilla(String dscplantilla) {
        this.dscplantilla = dscplantilla;
    }
    public char getEstadoplantilla() {
        return this.estadoplantilla;
    }
    
    public void setEstadoplantilla(char estadoplantilla) {
        this.estadoplantilla = estadoplantilla;
    }
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }




}


