package Modelo;
// Generated 10-20-2014 02:19:12 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Rolpersona generated by hbm2java
 */
public class Rolpersona  implements java.io.Serializable {


     private int idrolpersona;
     private String nmbrolpersona;
     private String dscrol;
     private Set personas = new HashSet(0);

    public Rolpersona() {
    }

	
    public Rolpersona(int idrolpersona) {
        this.idrolpersona = idrolpersona;
    }
    public Rolpersona(int idrolpersona, String nmbrolpersona, String dscrol, Set personas) {
       this.idrolpersona = idrolpersona;
       this.nmbrolpersona = nmbrolpersona;
       this.dscrol = dscrol;
       this.personas = personas;
    }
   
    public int getIdrolpersona() {
        return this.idrolpersona;
    }
    
    public void setIdrolpersona(int idrolpersona) {
        this.idrolpersona = idrolpersona;
    }
    public String getNmbrolpersona() {
        return this.nmbrolpersona;
    }
    
    public void setNmbrolpersona(String nmbrolpersona) {
        this.nmbrolpersona = nmbrolpersona;
    }
    public String getDscrol() {
        return this.dscrol;
    }
    
    public void setDscrol(String dscrol) {
        this.dscrol = dscrol;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


