package Modelo;
// Generated 10-20-2014 02:19:12 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipomodalidad generated by hbm2java
 */
public class Tipomodalidad  implements java.io.Serializable {


     private int idmodalidad;
     private String nmbmodalidad;
     private String dscmodalidad;
     private Set activos = new HashSet(0);

    public Tipomodalidad() {
    }

	
    public Tipomodalidad(int idmodalidad, String nmbmodalidad) {
        this.idmodalidad = idmodalidad;
        this.nmbmodalidad = nmbmodalidad;
    }
    public Tipomodalidad(int idmodalidad, String nmbmodalidad, String dscmodalidad, Set activos) {
       this.idmodalidad = idmodalidad;
       this.nmbmodalidad = nmbmodalidad;
       this.dscmodalidad = dscmodalidad;
       this.activos = activos;
    }
   
    public int getIdmodalidad() {
        return this.idmodalidad;
    }
    
    public void setIdmodalidad(int idmodalidad) {
        this.idmodalidad = idmodalidad;
    }
    public String getNmbmodalidad() {
        return this.nmbmodalidad;
    }
    
    public void setNmbmodalidad(String nmbmodalidad) {
        this.nmbmodalidad = nmbmodalidad;
    }
    public String getDscmodalidad() {
        return this.dscmodalidad;
    }
    
    public void setDscmodalidad(String dscmodalidad) {
        this.dscmodalidad = dscmodalidad;
    }
    public Set getActivos() {
        return this.activos;
    }
    
    public void setActivos(Set activos) {
        this.activos = activos;
    }




}


