package Modelo;
// Generated 10-20-2014 02:19:12 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadOrganizativa generated by hbm2java
 */
public class UnidadOrganizativa  implements java.io.Serializable {


     private int idunidad;
     private UnidadOrganizativa unidadOrganizativa;
     private String nmbunidad;
     private String dscunidad;
     private char estadounidad;
     private Set empleados = new HashSet(0);
     private Set unidadOrganizativas = new HashSet(0);

    public UnidadOrganizativa() {
    }

	
    public UnidadOrganizativa(int idunidad, String nmbunidad, char estadounidad) {
        this.idunidad = idunidad;
        this.nmbunidad = nmbunidad;
        this.estadounidad = estadounidad;
    }
    public UnidadOrganizativa(int idunidad, UnidadOrganizativa unidadOrganizativa, String nmbunidad, String dscunidad, char estadounidad, Set empleados, Set unidadOrganizativas) {
       this.idunidad = idunidad;
       this.unidadOrganizativa = unidadOrganizativa;
       this.nmbunidad = nmbunidad;
       this.dscunidad = dscunidad;
       this.estadounidad = estadounidad;
       this.empleados = empleados;
       this.unidadOrganizativas = unidadOrganizativas;
    }
   
    public int getIdunidad() {
        return this.idunidad;
    }
    
    public void setIdunidad(int idunidad) {
        this.idunidad = idunidad;
    }
    public UnidadOrganizativa getUnidadOrganizativa() {
        return this.unidadOrganizativa;
    }
    
    public void setUnidadOrganizativa(UnidadOrganizativa unidadOrganizativa) {
        this.unidadOrganizativa = unidadOrganizativa;
    }
    public String getNmbunidad() {
        return this.nmbunidad;
    }
    
    public void setNmbunidad(String nmbunidad) {
        this.nmbunidad = nmbunidad;
    }
    public String getDscunidad() {
        return this.dscunidad;
    }
    
    public void setDscunidad(String dscunidad) {
        this.dscunidad = dscunidad;
    }
    public char getEstadounidad() {
        return this.estadounidad;
    }
    
    public void setEstadounidad(char estadounidad) {
        this.estadounidad = estadounidad;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getUnidadOrganizativas() {
        return this.unidadOrganizativas;
    }
    
    public void setUnidadOrganizativas(Set unidadOrganizativas) {
        this.unidadOrganizativas = unidadOrganizativas;
    }




}


