package Modelo;
// Generated 10-20-2014 02:19:12 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private String idcategoria;
     private String nmbcategoria;
     private String dsccategoria;
     private Set detallecategorias = new HashSet(0);
     private Set activos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String idcategoria, String nmbcategoria, String dsccategoria) {
        this.idcategoria = idcategoria;
        this.nmbcategoria = nmbcategoria;
        this.dsccategoria = dsccategoria;
    }
    public Categoria(String idcategoria, String nmbcategoria, String dsccategoria, Set detallecategorias, Set activos) {
       this.idcategoria = idcategoria;
       this.nmbcategoria = nmbcategoria;
       this.dsccategoria = dsccategoria;
       this.detallecategorias = detallecategorias;
       this.activos = activos;
    }
   
    public String getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(String idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getNmbcategoria() {
        return this.nmbcategoria;
    }
    
    public void setNmbcategoria(String nmbcategoria) {
        this.nmbcategoria = nmbcategoria;
    }
    public String getDsccategoria() {
        return this.dsccategoria;
    }
    
    public void setDsccategoria(String dsccategoria) {
        this.dsccategoria = dsccategoria;
    }
    public Set getDetallecategorias() {
        return this.detallecategorias;
    }
    
    public void setDetallecategorias(Set detallecategorias) {
        this.detallecategorias = detallecategorias;
    }
    public Set getActivos() {
        return this.activos;
    }
    
    public void setActivos(Set activos) {
        this.activos = activos;
    }




}


