package Modelo;
// Generated 10-18-2014 09:44:40 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * Desafectacion generated by hbm2java
 */
public class Desafectacion  implements java.io.Serializable {


     private int iddesafectacion;
     private Empleado empleadoByEmpIdempleado;
     private Tipodesafectacion tipodesafectacion;
     private Empleado empleadoByIdempleado;
     private Persona persona;
     private BigDecimal ingresodesafectacion;
     private Date fechacrea;
     private Date fechaauto;
     private Integer numactajd;
     private Date fechaacta;
     private Integer numreporterobo;
     private Date fechadesafectacion;

    public Desafectacion() {
    }

	
    public Desafectacion(int iddesafectacion, Date fechacrea, Date fechadesafectacion) {
        this.iddesafectacion = iddesafectacion;
        this.fechacrea = fechacrea;
        this.fechadesafectacion = fechadesafectacion;
    }
    public Desafectacion(int iddesafectacion, Empleado empleadoByEmpIdempleado, Tipodesafectacion tipodesafectacion, Empleado empleadoByIdempleado, Persona persona, BigDecimal ingresodesafectacion, Date fechacrea, Date fechaauto, Integer numactajd, Date fechaacta, Integer numreporterobo, Date fechadesafectacion) {
       this.iddesafectacion = iddesafectacion;
       this.empleadoByEmpIdempleado = empleadoByEmpIdempleado;
       this.tipodesafectacion = tipodesafectacion;
       this.empleadoByIdempleado = empleadoByIdempleado;
       this.persona = persona;
       this.ingresodesafectacion = ingresodesafectacion;
       this.fechacrea = fechacrea;
       this.fechaauto = fechaauto;
       this.numactajd = numactajd;
       this.fechaacta = fechaacta;
       this.numreporterobo = numreporterobo;
       this.fechadesafectacion = fechadesafectacion;
    }
   
    public int getIddesafectacion() {
        return this.iddesafectacion;
    }
    
    public void setIddesafectacion(int iddesafectacion) {
        this.iddesafectacion = iddesafectacion;
    }
    public Empleado getEmpleadoByEmpIdempleado() {
        return this.empleadoByEmpIdempleado;
    }
    
    public void setEmpleadoByEmpIdempleado(Empleado empleadoByEmpIdempleado) {
        this.empleadoByEmpIdempleado = empleadoByEmpIdempleado;
    }
    public Tipodesafectacion getTipodesafectacion() {
        return this.tipodesafectacion;
    }
    
    public void setTipodesafectacion(Tipodesafectacion tipodesafectacion) {
        this.tipodesafectacion = tipodesafectacion;
    }
    public Empleado getEmpleadoByIdempleado() {
        return this.empleadoByIdempleado;
    }
    
    public void setEmpleadoByIdempleado(Empleado empleadoByIdempleado) {
        this.empleadoByIdempleado = empleadoByIdempleado;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public BigDecimal getIngresodesafectacion() {
        return this.ingresodesafectacion;
    }
    
    public void setIngresodesafectacion(BigDecimal ingresodesafectacion) {
        this.ingresodesafectacion = ingresodesafectacion;
    }
    public Date getFechacrea() {
        return this.fechacrea;
    }
    
    public void setFechacrea(Date fechacrea) {
        this.fechacrea = fechacrea;
    }
    public Date getFechaauto() {
        return this.fechaauto;
    }
    
    public void setFechaauto(Date fechaauto) {
        this.fechaauto = fechaauto;
    }
    public Integer getNumactajd() {
        return this.numactajd;
    }
    
    public void setNumactajd(Integer numactajd) {
        this.numactajd = numactajd;
    }
    public Date getFechaacta() {
        return this.fechaacta;
    }
    
    public void setFechaacta(Date fechaacta) {
        this.fechaacta = fechaacta;
    }
    public Integer getNumreporterobo() {
        return this.numreporterobo;
    }
    
    public void setNumreporterobo(Integer numreporterobo) {
        this.numreporterobo = numreporterobo;
    }
    public Date getFechadesafectacion() {
        return this.fechadesafectacion;
    }
    
    public void setFechadesafectacion(Date fechadesafectacion) {
        this.fechadesafectacion = fechadesafectacion;
    }




}


