package Modelo;
// Generated 10-18-2014 09:44:40 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Detallecategoria generated by hbm2java
 */
public class Detallecategoria  implements java.io.Serializable {


     private int iddetallecategoria;
     private Categoria categoria;
     private String dscdetalle;
     private Set especificacionactivos = new HashSet(0);

    public Detallecategoria() {
    }

	
    public Detallecategoria(int iddetallecategoria, Categoria categoria, String dscdetalle) {
        this.iddetallecategoria = iddetallecategoria;
        this.categoria = categoria;
        this.dscdetalle = dscdetalle;
    }
    public Detallecategoria(int iddetallecategoria, Categoria categoria, String dscdetalle, Set especificacionactivos) {
       this.iddetallecategoria = iddetallecategoria;
       this.categoria = categoria;
       this.dscdetalle = dscdetalle;
       this.especificacionactivos = especificacionactivos;
    }
   
    public int getIddetallecategoria() {
        return this.iddetallecategoria;
    }
    
    public void setIddetallecategoria(int iddetallecategoria) {
        this.iddetallecategoria = iddetallecategoria;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getDscdetalle() {
        return this.dscdetalle;
    }
    
    public void setDscdetalle(String dscdetalle) {
        this.dscdetalle = dscdetalle;
    }
    public Set getEspecificacionactivos() {
        return this.especificacionactivos;
    }
    
    public void setEspecificacionactivos(Set especificacionactivos) {
        this.especificacionactivos = especificacionactivos;
    }




}


