package Modelo;
// Generated 10-20-2014 02:19:12 PM by Hibernate Tools 3.6.0



/**
 * Especificacionactivo generated by hbm2java
 */
public class Especificacionactivo  implements java.io.Serializable {


     private int idespecificacion;
     private Activo activo;
     private Detallecategoria detallecategoria;
     private String valor;

    public Especificacionactivo() {
    }

	
    public Especificacionactivo(int idespecificacion, String valor) {
        this.idespecificacion = idespecificacion;
        this.valor = valor;
    }
    public Especificacionactivo(int idespecificacion, Activo activo, Detallecategoria detallecategoria, String valor) {
       this.idespecificacion = idespecificacion;
       this.activo = activo;
       this.detallecategoria = detallecategoria;
       this.valor = valor;
    }
   
    public int getIdespecificacion() {
        return this.idespecificacion;
    }
    
    public void setIdespecificacion(int idespecificacion) {
        this.idespecificacion = idespecificacion;
    }
    public Activo getActivo() {
        return this.activo;
    }
    
    public void setActivo(Activo activo) {
        this.activo = activo;
    }
    public Detallecategoria getDetallecategoria() {
        return this.detallecategoria;
    }
    
    public void setDetallecategoria(Detallecategoria detallecategoria) {
        this.detallecategoria = detallecategoria;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


