package Modelo;
// Generated 10-18-2014 09:44:40 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Inventario generated by hbm2java
 */
public class Inventario  implements java.io.Serializable {


     private int idinventario;
     private Activo activo;
     private Empleado empleadoByEmpIdempleado;
     private Empleado empleadoByIdempleado;
     private Date fecharealizacion;
     private Date horarealizacion;
     private char estadobienactual;
     private String observacion;
     private Character poseevineta;
     private Character existe;
     private Character bajocustodia;
     private Character ubicacionfisica;
     private String justificaciondiferencias;
     private Date fechajustificacion;

    public Inventario() {
    }

	
    public Inventario(int idinventario, Activo activo, Empleado empleadoByIdempleado, Date fecharealizacion, Date horarealizacion, char estadobienactual) {
        this.idinventario = idinventario;
        this.activo = activo;
        this.empleadoByIdempleado = empleadoByIdempleado;
        this.fecharealizacion = fecharealizacion;
        this.horarealizacion = horarealizacion;
        this.estadobienactual = estadobienactual;
    }
    public Inventario(int idinventario, Activo activo, Empleado empleadoByEmpIdempleado, Empleado empleadoByIdempleado, Date fecharealizacion, Date horarealizacion, char estadobienactual, String observacion, Character poseevineta, Character existe, Character bajocustodia, Character ubicacionfisica, String justificaciondiferencias, Date fechajustificacion) {
       this.idinventario = idinventario;
       this.activo = activo;
       this.empleadoByEmpIdempleado = empleadoByEmpIdempleado;
       this.empleadoByIdempleado = empleadoByIdempleado;
       this.fecharealizacion = fecharealizacion;
       this.horarealizacion = horarealizacion;
       this.estadobienactual = estadobienactual;
       this.observacion = observacion;
       this.poseevineta = poseevineta;
       this.existe = existe;
       this.bajocustodia = bajocustodia;
       this.ubicacionfisica = ubicacionfisica;
       this.justificaciondiferencias = justificaciondiferencias;
       this.fechajustificacion = fechajustificacion;
    }
   
    public int getIdinventario() {
        return this.idinventario;
    }
    
    public void setIdinventario(int idinventario) {
        this.idinventario = idinventario;
    }
    public Activo getActivo() {
        return this.activo;
    }
    
    public void setActivo(Activo activo) {
        this.activo = activo;
    }
    public Empleado getEmpleadoByEmpIdempleado() {
        return this.empleadoByEmpIdempleado;
    }
    
    public void setEmpleadoByEmpIdempleado(Empleado empleadoByEmpIdempleado) {
        this.empleadoByEmpIdempleado = empleadoByEmpIdempleado;
    }
    public Empleado getEmpleadoByIdempleado() {
        return this.empleadoByIdempleado;
    }
    
    public void setEmpleadoByIdempleado(Empleado empleadoByIdempleado) {
        this.empleadoByIdempleado = empleadoByIdempleado;
    }
    public Date getFecharealizacion() {
        return this.fecharealizacion;
    }
    
    public void setFecharealizacion(Date fecharealizacion) {
        this.fecharealizacion = fecharealizacion;
    }
    public Date getHorarealizacion() {
        return this.horarealizacion;
    }
    
    public void setHorarealizacion(Date horarealizacion) {
        this.horarealizacion = horarealizacion;
    }
    public char getEstadobienactual() {
        return this.estadobienactual;
    }
    
    public void setEstadobienactual(char estadobienactual) {
        this.estadobienactual = estadobienactual;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Character getPoseevineta() {
        return this.poseevineta;
    }
    
    public void setPoseevineta(Character poseevineta) {
        this.poseevineta = poseevineta;
    }
    public Character getExiste() {
        return this.existe;
    }
    
    public void setExiste(Character existe) {
        this.existe = existe;
    }
    public Character getBajocustodia() {
        return this.bajocustodia;
    }
    
    public void setBajocustodia(Character bajocustodia) {
        this.bajocustodia = bajocustodia;
    }
    public Character getUbicacionfisica() {
        return this.ubicacionfisica;
    }
    
    public void setUbicacionfisica(Character ubicacionfisica) {
        this.ubicacionfisica = ubicacionfisica;
    }
    public String getJustificaciondiferencias() {
        return this.justificaciondiferencias;
    }
    
    public void setJustificaciondiferencias(String justificaciondiferencias) {
        this.justificaciondiferencias = justificaciondiferencias;
    }
    public Date getFechajustificacion() {
        return this.fechajustificacion;
    }
    
    public void setFechajustificacion(Date fechajustificacion) {
        this.fechajustificacion = fechajustificacion;
    }




}


