package Modelo;
// Generated 10-20-2014 02:19:12 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idpersona;
     private Persona persona;
     private Tipopersona tipopersona;
     private Rolpersona rolpersona;
     private String nombrerazon;
     private String direccion;
     private String telefono;
     private String correo;
     private String nit;
     private String dui;
     private Set desafectacions = new HashSet(0);
     private Set activos = new HashSet(0);
     private Set personas = new HashSet(0);
     private Set mantenimientos = new HashSet(0);

    public Persona() {
    }

	
    public Persona(int idpersona, Tipopersona tipopersona, String nombrerazon, String direccion, String telefono, String correo, String nit, String dui) {
        this.idpersona = idpersona;
        this.tipopersona = tipopersona;
        this.nombrerazon = nombrerazon;
        this.direccion = direccion;
        this.telefono = telefono;
        this.correo = correo;
        this.nit = nit;
        this.dui = dui;
    }
    public Persona(int idpersona, Persona persona, Tipopersona tipopersona, Rolpersona rolpersona, String nombrerazon, String direccion, String telefono, String correo, String nit, String dui, Set desafectacions, Set activos, Set personas, Set mantenimientos) {
       this.idpersona = idpersona;
       this.persona = persona;
       this.tipopersona = tipopersona;
       this.rolpersona = rolpersona;
       this.nombrerazon = nombrerazon;
       this.direccion = direccion;
       this.telefono = telefono;
       this.correo = correo;
       this.nit = nit;
       this.dui = dui;
       this.desafectacions = desafectacions;
       this.activos = activos;
       this.personas = personas;
       this.mantenimientos = mantenimientos;
    }
   
    public int getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(int idpersona) {
        this.idpersona = idpersona;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Tipopersona getTipopersona() {
        return this.tipopersona;
    }
    
    public void setTipopersona(Tipopersona tipopersona) {
        this.tipopersona = tipopersona;
    }
    public Rolpersona getRolpersona() {
        return this.rolpersona;
    }
    
    public void setRolpersona(Rolpersona rolpersona) {
        this.rolpersona = rolpersona;
    }
    public String getNombrerazon() {
        return this.nombrerazon;
    }
    
    public void setNombrerazon(String nombrerazon) {
        this.nombrerazon = nombrerazon;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public Set getDesafectacions() {
        return this.desafectacions;
    }
    
    public void setDesafectacions(Set desafectacions) {
        this.desafectacions = desafectacions;
    }
    public Set getActivos() {
        return this.activos;
    }
    
    public void setActivos(Set activos) {
        this.activos = activos;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }
    public Set getMantenimientos() {
        return this.mantenimientos;
    }
    
    public void setMantenimientos(Set mantenimientos) {
        this.mantenimientos = mantenimientos;
    }




}


