package Modelo;
// Generated 10-18-2014 09:44:40 PM by Hibernate Tools 3.6.0



/**
 * Rolpersona generated by hbm2java
 */
public class Rolpersona  implements java.io.Serializable {


     private int idrolpersona;
     private Persona persona;
     private String nmbrolpersona;
     private String dscrol;

    public Rolpersona() {
    }

	
    public Rolpersona(int idrolpersona, Persona persona) {
        this.idrolpersona = idrolpersona;
        this.persona = persona;
    }
    public Rolpersona(int idrolpersona, Persona persona, String nmbrolpersona, String dscrol) {
       this.idrolpersona = idrolpersona;
       this.persona = persona;
       this.nmbrolpersona = nmbrolpersona;
       this.dscrol = dscrol;
    }
   
    public int getIdrolpersona() {
        return this.idrolpersona;
    }
    
    public void setIdrolpersona(int idrolpersona) {
        this.idrolpersona = idrolpersona;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getNmbrolpersona() {
        return this.nmbrolpersona;
    }
    
    public void setNmbrolpersona(String nmbrolpersona) {
        this.nmbrolpersona = nmbrolpersona;
    }
    public String getDscrol() {
        return this.dscrol;
    }
    
    public void setDscrol(String dscrol) {
        this.dscrol = dscrol;
    }




}


