package Modelo;
// Generated 10-18-2014 09:44:40 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoestado generated by hbm2java
 */
public class Tipoestado  implements java.io.Serializable {


     private int idtipoestado;
     private String nmbtipoestado;
     private String dsctipoestado;
     private Set activos = new HashSet(0);

    public Tipoestado() {
    }

	
    public Tipoestado(int idtipoestado, String nmbtipoestado, String dsctipoestado) {
        this.idtipoestado = idtipoestado;
        this.nmbtipoestado = nmbtipoestado;
        this.dsctipoestado = dsctipoestado;
    }
    public Tipoestado(int idtipoestado, String nmbtipoestado, String dsctipoestado, Set activos) {
       this.idtipoestado = idtipoestado;
       this.nmbtipoestado = nmbtipoestado;
       this.dsctipoestado = dsctipoestado;
       this.activos = activos;
    }
   
    public int getIdtipoestado() {
        return this.idtipoestado;
    }
    
    public void setIdtipoestado(int idtipoestado) {
        this.idtipoestado = idtipoestado;
    }
    public String getNmbtipoestado() {
        return this.nmbtipoestado;
    }
    
    public void setNmbtipoestado(String nmbtipoestado) {
        this.nmbtipoestado = nmbtipoestado;
    }
    public String getDsctipoestado() {
        return this.dsctipoestado;
    }
    
    public void setDsctipoestado(String dsctipoestado) {
        this.dsctipoestado = dsctipoestado;
    }
    public Set getActivos() {
        return this.activos;
    }
    
    public void setActivos(Set activos) {
        this.activos = activos;
    }




}


