package Modelo;
// Generated 10-20-2014 02:19:12 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoactivo generated by hbm2java
 */
public class Tipoactivo  implements java.io.Serializable {


     private int idtipoactivo;
     private String nmbactivo;
     private Integer vidautil;
     private Set activos = new HashSet(0);

    public Tipoactivo() {
    }

	
    public Tipoactivo(int idtipoactivo) {
        this.idtipoactivo = idtipoactivo;
    }
    public Tipoactivo(int idtipoactivo, String nmbactivo, Integer vidautil, Set activos) {
       this.idtipoactivo = idtipoactivo;
       this.nmbactivo = nmbactivo;
       this.vidautil = vidautil;
       this.activos = activos;
    }
   
    public int getIdtipoactivo() {
        return this.idtipoactivo;
    }
    
    public void setIdtipoactivo(int idtipoactivo) {
        this.idtipoactivo = idtipoactivo;
    }
    public String getNmbactivo() {
        return this.nmbactivo;
    }
    
    public void setNmbactivo(String nmbactivo) {
        this.nmbactivo = nmbactivo;
    }
    public Integer getVidautil() {
        return this.vidautil;
    }
    
    public void setVidautil(Integer vidautil) {
        this.vidautil = vidautil;
    }
    public Set getActivos() {
        return this.activos;
    }
    
    public void setActivos(Set activos) {
        this.activos = activos;
    }




}


