package Modelo;
// Generated 10-20-2014 02:19:12 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipopersona generated by hbm2java
 */
public class Tipopersona  implements java.io.Serializable {


     private int idtipopersona;
     private String nmbtipopersona;
     private String dsctipopersona;
     private Set personas = new HashSet(0);

    public Tipopersona() {
    }

	
    public Tipopersona(int idtipopersona, String nmbtipopersona) {
        this.idtipopersona = idtipopersona;
        this.nmbtipopersona = nmbtipopersona;
    }
    public Tipopersona(int idtipopersona, String nmbtipopersona, String dsctipopersona, Set personas) {
       this.idtipopersona = idtipopersona;
       this.nmbtipopersona = nmbtipopersona;
       this.dsctipopersona = dsctipopersona;
       this.personas = personas;
    }
   
    public int getIdtipopersona() {
        return this.idtipopersona;
    }
    
    public void setIdtipopersona(int idtipopersona) {
        this.idtipopersona = idtipopersona;
    }
    public String getNmbtipopersona() {
        return this.nmbtipopersona;
    }
    
    public void setNmbtipopersona(String nmbtipopersona) {
        this.nmbtipopersona = nmbtipopersona;
    }
    public String getDsctipopersona() {
        return this.dsctipopersona;
    }
    
    public void setDsctipopersona(String dsctipopersona) {
        this.dsctipopersona = dsctipopersona;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


