package Modelo;
// Generated 10-20-2014 02:19:12 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idusuario;
     private Empleado empleado;
     private Rol rol;
     private String password;
     private char estadousuario;
     private Set actividads = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String idusuario, Rol rol, String password, char estadousuario) {
        this.idusuario = idusuario;
        this.rol = rol;
        this.password = password;
        this.estadousuario = estadousuario;
    }
    public Usuario(String idusuario, Empleado empleado, Rol rol, String password, char estadousuario, Set actividads) {
       this.idusuario = idusuario;
       this.empleado = empleado;
       this.rol = rol;
       this.password = password;
       this.estadousuario = estadousuario;
       this.actividads = actividads;
    }
   
    public String getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public char getEstadousuario() {
        return this.estadousuario;
    }
    
    public void setEstadousuario(char estadousuario) {
        this.estadousuario = estadousuario;
    }
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }




}


